### ISSUE TITLE
spec: Clarify literal parentheses vs. statement groups in grammar spec

### ISSUE THREAD

**Issue by boqwxp** [chipsalliance/firrtl-spec#7]
Current text
----

See `spec.pdf`, section 14.2, "Concrete Syntax Tree".  For example, see the definition for *circuit* on the very first line:

> *circuit* = `circuit` *id* : [[*info*]]? ([[module]]...)

It is apparent from Listing 85 above that the parentheses are not literal, but represent a statement group.  However, see the definition for *exp*/*primop* below:

> *exp* = *primop* ( [[*exp*]]..., [[*int*]]...)

From the final line of Listing 85, it appears that *these* parentheses are literal parentheses.

Desired text
----

It would be very helpful to revise the spec to make explicit where parentheses are literal symbols and where they represent statement groups.

**Comment by seldridge** [comment]
Thanks for reporting this and apologies for the extremely long response time!

We've migrated the spec to Markdown and part of that was removing the LaTeX macro-based "Concrete Syntax Tree" for a more standardized BNF/EBNF description.  This is fixed in the latest [v0.3.0 release](https://github.com/chipsalliance/firrtl-spec/releases/download/v0.3.0/spec.pdf).

E.g., for the two examples you mention, these are now documented as:

<img width="502" alt="Screen Shot 2022-03-04 at 18 55 03" src="https://user-images.githubusercontent.com/1018530/156857454-a411b464-ed79-4bea-a537-c65dd878e1c0.png">

And:

<img width="604" alt="Screen Shot 2022-03-04 at 18 56 42" src="https://user-images.githubusercontent.com/1018530/156857509-616a3980-bf2d-4919-8550-ba532b8cbdbf.png">
